/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_djhu_utils_url2pdf_jni_UrlToPdf4j */

#ifndef _Included_com_djhu_utils_url2pdf_jni_UrlToPdf4j
#define _Included_com_djhu_utils_url2pdf_jni_UrlToPdf4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_djhu_utils_url2pdf_jni_UrlToPdf4j
 * Method:    nativeDjhuPDFInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_djhu_utils_url2pdf_jni_UrlToPdf4j_nativeDjhuPDFInit
  (JNIEnv *, jclass);

/*
 * Class:     com_djhu_utils_url2pdf_jni_UrlToPdf4j
 * Method:    nativeDjhuPDFDeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_djhu_utils_url2pdf_jni_UrlToPdf4j_nativeDjhuPDFDeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_djhu_utils_url2pdf_jni_UrlToPdf4j
 * Method:    nativeDjhuUrlToPdf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_djhu_utils_url2pdf_jni_UrlToPdf4j_nativeDjhuUrlToPdf
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_djhu_utils_url2pdf_jni_UrlToPdf4j
 * Method:    nativeDjhuUrlToPdfParam
 * Signature: (Lcom/djhu/utils/url2pdf/jni/PDFParam;)I
 */
JNIEXPORT jint JNICALL Java_com_djhu_utils_url2pdf_jni_UrlToPdf4j_nativeDjhuUrlToPdfParam
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
